# Generated by Django 4.2.14 on 2024-08-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=10, verbose_name='SKU')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ціна')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['sku'],
            },
        ),
    ]
