# Generated by Django 4.2.15 on 2025-03-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Напрямок')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=10, verbose_name='SKU')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ціна')),
                ('directions', models.ManyToManyField(blank=True, related_name='goods', to='goods.direction', verbose_name='Напрямки')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['sku'],
            },
        ),
    ]
