# Generated by Django 4.2.15 on 2024-01-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='difference_count',
            field=models.IntegerField(default=0, verbose_name='Кількість відхилень по позиції'),
        ),
    ]
