# Generated by Django 4.2.15 on 2024-08-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_difference_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Напрямок')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='directions',
            field=models.ManyToManyField(blank=True, null=True, related_name='directions', to='goods.direction', verbose_name='Напрямки'),
        ),
    ]
