# Generated by Django 4.2.15 on 2024-09-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_direction_goods_directions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='difference_count',
        ),
    ]
