# Generated by Django 4.2.15 on 2025-03-18 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Сайт')),
                ('link', models.URLField(max_length=500, verbose_name='Посилання')),
                ('tags_trail', models.CharField(blank=True, max_length=500, verbose_name='Шлях до контейнера')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.direction', verbose_name='Напрямок')),
            ],
        ),
        migrations.CreateModel(
            name='SiteGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500, verbose_name='Посилання на товар')),
                ('price_on_site', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ціна на сайті')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Розбіжність')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_goods', to='sites.site')),
            ],
        ),
    ]
