# Generated by Django 4.2.14 on 2024-08-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitegoods',
            name='price_on_site',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
