# Generated by Django 4.2.14 on 2024-08-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_sitegoods_price_on_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='tags_trail',
            field=models.CharField(blank=True, max_length=500, verbose_name='Шлях до контейнера'),
        ),
        migrations.AlterField(
            model_name='sitegoods',
            name='link',
            field=models.URLField(max_length=500, verbose_name='Посилання на товар'),
        ),
        migrations.AlterField(
            model_name='sitegoods',
            name='price_on_site',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ціна на сайті'),
        ),
    ]
