# Generated by Django 4.2.14 on 2024-08-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_site_tags_trail_alter_sitegoods_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitegoods',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_goods', to='sites.site'),
        ),
    ]
