# Generated by Django 5.0.8 on 2024-08-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_sitegoods_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitegoods',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Розбіжність'),
        ),
    ]
