# Generated by Django 4.2.15 on 2024-08-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_direction_goods_directions'),
        ('sites', '0006_direction_site_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.direction', verbose_name='Напрямок'),
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
    ]
